# Generated by Django 4.1 on 2024-02-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Tela", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="API",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=30)),
            ],
        ),
    ]
